# Generated by Django 5.1.4 on 2025-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
